# This is a basic workflow to help you get started with Actions

name: IaC clean

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clean:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init -backend-config=env/dev/config.s3.tfbackend -upgrade=true -no-color -input=false
      - name: Destroy IaC resources
        id: destroy
        run: terraform apply -destroy -input=false -var-file=env/dev/terraform.tfvars -auto-approve
